version: '3.8'

services:
  postgres:
    image: postgres:17.5
    container_name: pakhub-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - '${POSTGRES_PORT:-5432}:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - pakhub-network

volumes:
  postgres_data:
    driver: local

networks:
  pakhub-network:
    driver: bridge
